src/Entity/Addresse.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\AddresseRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AddresseRepository::class)
 */
#[ApiResource(
    normalizationContext: ['groups' => ['Property'], ['Addresse']],
    denormalizationContext: ['groups' => ['Property'], ['Addresse']]
)]
class Addresse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Groups("Property","Reservation")
     */

    /* #[Assert\NotBlank(message: "Veuillez remplir les champs requis")]
    #[Assert\NotNull(message: "Veuillez remplir les champs requis")]
    #[Assert\Type(type: 'integer', message: "Veuillez remplir le champ avec une valeur correcte")] */
    private $street_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("Property","Reservation")
     */
    /* #[Assert\NotBlank(message: "Veuillez remplir les champs requis")]
    #[Assert\NotNull(message: "Veuillez remplir les champs requis")]
    #[Assert\Type(type: 'string', message: "Veuillez remplir le champ avec une valeur correcte")] */
    private $street_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("Property","Reservation")
     */
    /* #[Assert\NotBlank(message: "Veuillez remplir les champs requis")]
    #[Assert\NotNull(message: "Veuillez remplir les champs requis")]
    #[Assert\Type(type: 'string', message: "Veuillez remplir le champ avec une valeur correcte")] */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("Property","Reservation")
     */
    /* #[Assert\NotBlank(message: "Veuillez remplir les champs requis")]
    #[Assert\NotNull(message: "Veuillez remplir les champs requis")]
    #[Assert\Type(type: 'string', message: "Veuillez remplir le champ avec une valeur correcte")] */
    private $code_zip;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("Property","Reservation")
     */
    /* #[Assert\NotBlank(message: "Veuillez remplir les champs requis")]
    #[Assert\NotNull(message: "Veuillez remplir les champs requis")]
    #[Assert\Type(type: 'string', message: "Veuillez remplir le champ avec une valeur correcte")] */
    private $country;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreetNumber(): ?int
    {
        return $this->street_number;
    }

    public function setStreetNumber(int $street_number): self
    {
        $this->street_number = $street_number;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->street_name;
    }

    public function setStreetName(string $street_name): self
    {
        $this->street_name = $street_name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCodeZip(): ?string
    {
        return $this->code_zip;
    }

    public function setCodeZip(string $code_zip): self
    {
        $this->code_zip = $code_zip;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Serializer\Filter\PropertyFilter;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
#[ApiResource(
    normalizationContext: ["groups" => "user:read"],
    denormalizationContext: ["groups" => "user:write"]
)]

#[ApiFilter(PropertyFilter::class)]

#[UniqueEntity(['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups({"user:read", "user:write"})
     * @Assert\NotBlank(message="Email")
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Groups({"user:read", "user:write"})
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Groups({"user:write"})
     * @Assert\NotBlank()
     * @SerializedName("password")
     */
    private $password;


    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user:read", "user:write"})
     * @Assert\NotBlank(message="Prénom")
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user:read", "user:write"})
     * @Assert\NotBlank(message="Nom")
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user:read", "user:write"})
     * @Assert\NotBlank(message="Sexe")
     */
    private $sex;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user:read", "user:write"})
     * @Assert\NotBlank(message="Tél")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"user:read"})
     */
    private $apiToken;

    /**
     * @ORM\OneToOne(targetEntity=Addresse::class, cascade={"persist", "remove"})
     * @Groups({"user:read", "user:write"})
     */
    private $addresse;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="user")
     */
    private $sends;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="user")
     */
    private $receives;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status = 1;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = true;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="user")
     */
    private $reservations;

    /**
     * @ORM\Column(type="date",nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\OneToMany(targetEntity=Property::class, mappedBy="user")
     */
    private $properties;

    /**
     * @ORM\OneToMany(targetEntity=Notification::class, mappedBy="user")
     */
    private $notifications;

    public function __construct()
    {
        $this->sends = new ArrayCollection();
        $this->receives = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->properties = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getApiToken(): ?string
    {
        return $this->apiToken;
    }

    public function setApiToken(?string $apiToken): self
    {
        $this->apiToken = $apiToken;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAddresse(): ?Addresse
    {
        return $this->addresse;
    }

    public function setAddresse(?Addresse $addresse): self
    {
        $this->addresse = $addresse;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getSends(): Collection
    {
        return $this->sends;
    }

    public function addSend(Message $send): self
    {
        if (!$this->sends->contains($send)) {
            $this->sends[] = $send;
            $send->setUser($this);
        }

        return $this;
    }

    public function removeSend(Message $send): self
    {
        if ($this->sends->removeElement($send)) {
            // set the owning side to null (unless already changed)
            if ($send->getUser() === $this) {
                $send->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getReceives(): Collection
    {
        return $this->receives;
    }

    public function addReceife(Message $receife): self
    {
        if (!$this->receives->contains($receife)) {
            $this->receives[] = $receife;
            $receife->setUser($this);
        }

        return $this;
    }

    public function removeReceife(Message $receife): self
    {
        if ($this->receives->removeElement($receife)) {
            // set the owning side to null (unless already changed)
            if ($receife->getUser() === $this) {
                $receife->setUser(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setUser($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    /**
     * @return Collection|Property[]
     */
    public function getProperties(): Collection
    {
        return $this->properties;
    }

    public function addProperty(Property $property): self
    {
        if (!$this->properties->contains($property)) {

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Addresse;
use App\Entity\User;
use App\Form\AddressType;
use App\Form\ProfileType;
use App\Form\RegistrationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    #[Route('/mon-profile', name: 'my-account')]
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            "user" => $this->getUser()
        ]);
    }

    #[Route('/mon-profile/adresse/modifier', name: 'edit-address')]
    public function editaddress(Request $request, EntityManagerInterface $entityManager): Response
    {
        $address = ($this->getUser()->getAddresse() !== null) ? $this->getUser()->getAddresse() : new Addresse();
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);
        $user = $this->getUser();
        $user->setAddresse($address);
        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($address);
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash("success", "Modifié avec succès");

            return $this->redirectToRoute('my-account');
        }

        return $this->render('user/editAddress.html.twig', [
            'addressForm' => $form->createView(),
        ]);
    }

    #[Route('/mon-profile/modifier', name: 'edit-account')]
    public function updateUser(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash("success", "Modifié avec succès");

            return $this->redirectToRoute('my-account');
        }

        return $this->render('user/editProfile.html.twig', [
            'profileForm' => $form->createView(),
        ]);
    }
}

templates/user/editAddress.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Compte{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="card">
            {{ form_start(addressForm) }}

            
                <h1 class="h1 card-header text-center text-light bg-dark py-3">Mon Adresse</h1>
               <div class="card-body py-3">
                <div class="row">
                <div class="col-6">
                    <div class="form-floating mb-3">
                        {{ form_widget(addressForm.street_number) }}
                        {{ form_label(addressForm.street_number) }}
                        {{ form_errors(addressForm.street_number) }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        {{ form_widget(addressForm.street_name) }}
                        {{ form_label(addressForm.street_name) }}
                        {{ form_errors(addressForm.street_name) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <div class="form-floating mb-3">
                        {{ form_widget(addressForm.city) }}
                        {{ form_label(addressForm.city) }}
                        {{ form_errors(addressForm.city) }}
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-floating mb-3">
                        {{ form_widget(addressForm.code_zip) }}
                        {{ form_label(addressForm.code_zip) }}
                        {{ form_errors(addressForm.code_zip) }}
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-floating mb-3">
                        {{ form_widget(addressForm.country) }}
                        {{ form_label(addressForm.country) }}
                        {{ form_errors(addressForm.country) }}
                    </div>
                </div>
            </div>
                <div class="col-12 align-content-center d-flex">
                    <a href="{{ path('my-account') }}" class="btn btn-danger w-100 me-3">Annuler</a>
                    <button type="submit" class="btn btn-success w-100">Modifier</button>
                </div>
            </div>
            {{ form_end(addressForm) }}
        </div>
    </div>
</div>
{% endblock %}

templates/user/editProfile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Compte{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="card">
            {{ form_start(profileForm) }}
            
                <h1 class="h1 card-header text-center text-light bg-dark py-3">Mon Profile</h1>
                <div class="card-body py-3">

                    <div class="row">
                <div class="col-6">
                    <div class="form-floating mb-3">
                        {{ form_widget(profileForm.firstName) }}
                        {{ form_label(profileForm.firstName) }}
                        {{ form_errors(profileForm.firstName) }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        {{ form_widget(profileForm.lastName) }}
                        {{ form_label(profileForm.lastName) }}
                        {{ form_errors(profileForm.lastName) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <div class="form-floating mb-3">
                        {{ form_widget(profileForm.sex) }}
                        {{ form_label(profileForm.sex) }}
                        {{ form_errors(profileForm.sex) }}
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-floating mb-3">
                        {{ form_widget(profileForm.phone) }}
                        {{ form_label(profileForm.phone) }}
                        {{ form_errors(profileForm.phone) }}
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-floating mb-3">
                        {{ form_widget(profileForm.email) }}
                        {{ form_label(profileForm.email) }}
                        {{ form_errors(profileForm.email) }}
                    </div>
                </div>
            </div>
                <div class="col-6">
                    <div class="mb-3">
                        {{ form_label(profileForm.birthDate) }}
                        {{ form_widget(profileForm.birthDate) }}
                        {{ form_errors(profileForm.birthDate) }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        {{ form_row(profileForm.password) }}
                    </div>
                </div>
                <div class="col-12 align-content-center d-flex">
                    <a href="{{ path('my-account') }}" class="btn btn-danger w-100 me-3">Annuler</a>
                    <button type="submit" class="btn btn-success w-100">Modifier</button>
                </div>
            </div>
            {{ form_end(profileForm) }}
        </div>
    </div>
</div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Compte{% endblock %}

{% block body %}
<div class="container">
    <div class="row mt-5">
        
        <div class="row">
          <div class="card-header">
             <h1 class=" text-center bg-dark text-light py-3">Paramètres généraux du compte</h1>
          </div>
       </div>  

        <div class="row">
                <div class="card-header">
                   <h2 class="text-center py-1">Mon Profile</h2>
                </div>
            <div class="card py-5">
             <div class="row">
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="prenom" value="{{user.firstName}}" readonly>
                        <label for="prenom">Prénom</label>
                      
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="nom" value="{{ user.lastName }}" readonly>
                        <label for="nom">Nom</label>
                    </div>
                </div>
             </div>
             <div class="row">
                
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <select class="form-select" disabled>
                            <option value="{{ user.sex }}" selected>{{ user.sex }}</option>
                        </select>
                        <label>Sexe</label>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="tel"  id="tel" class="form-control" value="{{ user.phone }}" readonly>
                        <label for="tel">Tél</label>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="email" id="email" class="form-control" value="{{ user.email }}" readonly>
                        <label for="email">Email</label>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3 ">
                        <input type="date" class="form-control" id="dateNaissance" value="{{ user.birthDate|date("Y-m-d") }}" readonly>
                        <label for="dateNaissance" >Date naissance</label>
                    </div>
                </div>
            </div>
                <div class=" align-content-center d-flex">
                    <a class="btn btn-primary w-100 " href="{{ path('edit-account') }}">Modifier Mon Profile</a>
                </div>
            </div>
        </div>
       
            <div class="row">
                <div class="card-header">
                <h2 class="text-center py-1">Mon Adresse</h2>
            </div>
            <div class="card py-5">
                <div class="row">
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="Nrue" value="{{ user.addresse.streetNumber ?? '' }}" readonly>
                        <label for="Nrue">N° rue</label>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="rue" value="{{ user.addresse.streetName ?? '' }}" readonly>
                        <label for="rue">Rue</label>
                    </div>
                </div>
              </div>

               <div class="row">
                <div class="col-4">
                    <div class="form-floating mb-3">
                        <input type="text" id="city" class="form-control" value="{{ user.addresse.city  ?? '' }}" readonly>
                        <label for="city">Ville</label>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-floating mb-3">
                        <input type="text" id="postal" class="form-control" value="{{ user.addresse.codeZip ?? ''}}" readonly>
                        <label for="postal">C.P</label>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-floating mb-3">
                        <select class="form-select" disabled>
                            <option value="{{ user.addresse.country ?? 'FR' }}" selected>{{ user.addresse.country ?? 'FR' }}</option>
                        </select>
                        <label>Pays</label>
                    </div>
                </div>
               </div>

                <div class="align-content-center d-flex">
                    <a href="{{ path('edit-address') }}" class="btn btn-primary w-100">Modifier Mon Adresse </a>
                </div>
            </div>
       </div>
    </div>
</div>
</div>
{% endblock %}